### PR TITLE
fix: required constraint for objects

### LINKED ISSUE #138: Bean Validation on Nested Fields doesn't work
I'm trying to use ConstrainedFields for Bean Validation but unable to get it to work.

```xml
<restdocs-api-spec.version>0.9.9</restdocs-api-spec.version>
```

As you can see below, CreateBookRequestDto has property 'author' and it should not be null.
```java
@Value
@Builder
public class CreateBookRequestDto {
    @NotEmpty String title;
    @NotNull @Valid AuthorDto author;
}

@Value
@Builder
@Validated
public class AuthorDto {
    @NotEmpty String firstName;
    @NotEmpty String lastName;
}
```

```java
@Test
    public void create() throws Exception {
        //when
        BookDto book = BookDto.builder().isbn("0-9705-6867-3").title("A Time To Kill").author(AuthorDto.builder().firstName("John").lastName("Grisham").build()).build();
        CreateBookRequestDto createBookRequestDto = CreateBookRequestDto.builder().title("A Time To Kill").author(AuthorDto.builder().firstName("John").lastName("Grisham").build()).build();
        when(bookService.create(any())).thenReturn(book);
        //then
        ConstrainedFields constrainedFields = new ConstrainedFields(CreateBookRequestDto.class);
        mvc
                .perform(post("/books")
                            .content(new ObjectMapper().writeValueAsBytes(createBookRequestDto))
                            .contentType(APPLICATION_JSON_VALUE)
                            .accept(APPLICATION_JSON_VALUE))
                .andExpect(status().isOk())
                .andDo(print())
                .andDo(
                        document(
                                "create-book",
                                resourceDetails().description("Create a book."),
                                requestFields(
                                        constrainedFields.withPath("title").description("The title of the book."),
                                        constrainedFields.withPath("author").description("The Author of the book."),
                                        constrainedFields.withMappedPath("author.firstName", "author").description("The author's first name."),
                                        constrainedFields.withMappedPath("author.lastName", "author").description("The author's last name.")
                                ),
                                responseFields(
                                        fieldWithPath("isbn").description("The ISBN of the book."),
                                        fieldWithPath("title").description("The title of the book."),
                                        fieldWithPath("author.firstName").description("The author's first name."),
                                        fieldWithPath("author.lastName").description("The author's last name.")
                                )
                        )
                );
    }
```

Generated openapi-3.0.yml file. As you can see below, author should be required but it doesn't show up in the required fields.

```yml
components:
  schemas:
    books-1095758460:
      required:
      - title
      type: object
      properties:
        author:
          required:
          - firstName
          - lastName
          type: object
          properties:
            lastName:
              type: string
              description: The author's last name.
            firstName:
              type: string
              description: The author's first name.
          description: The Author of the book.
        title:
          minLength: 1
          type: string
          description: The title of the book.
```

Is it a bug or am I missing something?

### PR DESCRIPTION
**Pull request by beltram**
Required constraint was not propagated to OpenApi schema for fields of type 'OBJECT'.  
Fixes #138

### CODE REVIEW

**Review by ozscheyge — APPROVED** [review]
Hey @beltram,

thanks for the fix! LGTM (one minor suggestion to reduce the parameter list)! 

Generated schema before fix (from the new test):
```
{
  "type" : "object",
  "properties" : {
    "obj" : {
      "description" : "some",
      "type" : "object",
      "properties" : {
        "field" : {
          "description" : "some",
          "type" : "string"
        }
      }
    }
  }
}
```

Generated schema after fix (from the new test):
```
{
  "type" : "object",
  "properties" : {
    "obj" : {
      "description" : "some",
      "type" : "object",
      "properties" : {
        "field" : {
          "description" : "some",
          "type" : "string"
        }
      }
    }
  },
  "required" : [ "obj" ]
}
```

File: restdocs-api-spec-jsonschema/src/main/kotlin/com/epages/restdocs/apispec/jsonschema/JsonSchemaFromFieldDescriptorsGenerator.kt [hunk 1]
```diff
@@ -146,6 +148,9 @@ class JsonSchemaFromFieldDescriptorsGenerator {
                     .build()
             )
         } else {
+            if (propertyField?.fieldDescriptor?.let { isRequired(it) } == true) {
```
Comment (ozscheyge) [inline restdocs-api-spec-jsonschema/src/main/kotlin/com/epages/restdocs/apispec/jsonschema/JsonSchemaFromFieldDescriptorsGenerator.kt:151]: This `== true` looks weird, but IntelliJ recommends this as a solution (problem is that `isRequired` requires a non-null type and returns a non-null Boolean, but the entire expression could evaluate to null already if the optional parameter is null).

Comment (beltram) [reply restdocs-api-spec-jsonschema/src/main/kotlin/com/epages/restdocs/apispec/jsonschema/JsonSchemaFromFieldDescriptorsGenerator.kt:151]: Yes that's a shorthand I use a lot in my daily Kotlin code to deal with nullable boolean. It's a shorthand for
```kotlin
if(nullableBoolean ?: false)
```
I can implement it as `?: false` or keep it the way it is, as you want
