### PR TITLE
[#113] Fix for application/x-www-form-urlencoded

### LINKED ISSUE #113: Empty schema in requestBody for application/x-www-form-urlencoded POST endpoints when using requestParameters as Spring REST Docs suggests
Hey!

Maybe I missed something, but for Spring REST Docs in order to generate examples for `application/x-www-urlencoded` you are using `requestParameters`: 

https://docs.spring.io/spring-restdocs/docs/current/reference/html5/#documenting-your-api-request-parameters

For POST methods it generates nice requests with *url encoded format*:

```
POST /oauth/token HTTP/1.1
Accept: application/json
Content-Type: application/x-www-form-urlencoded;charset=UTF-8
Authorization: Basic ....REDACTED...
Content-Length: 77
Host: localhost:8080

grant_type=password&scope=admin&username=...REDACTED...
```

However, in API specs we see this:

```
  /oauth/token:
    post:
    ...
      parameters:
      - name: grant_type
        in: query
        description: Type of the OAuth2 flow.
        required: true
        schema:
          type: string
      ...
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/oauth-token486549215'
            examples:
              oauth-token-200:
                value: 
                  ...
...
components:
  schemas:
    oauth-token486549215:
      type: object
```

Is there a way to move those fields from `parameters` section to the corresponding schema?

### PR DESCRIPTION
**Pull request by afronski**
Main point of this fix is to introduce proper payload documentation for OpenAPI 2.0 (changing type of parameter for a given Content-Type from query to formData) and OpenAPI 3.0 (moving payload definition from query parameters to requestBody).

It does not fix schema generation for OpenAPI 3.0 (it is still generating empty schema, although - it generates proper example if provided).

If merged, this closes #113

### CODE REVIEW

File: restdocs-api-spec-openapi-generator/src/test/kotlin/com/epages/restdocs/apispec/openapi2/OpenApi20GeneratorTest.kt [hunk 1]
```diff
@@ -230,6 +230,26 @@ class OpenApi20GeneratorTest {
         thenValidateOpenApi(openapi)
     }
 
+    @Test
+    fun `should handle urlencoded body in POST request as a formData not query string`() {
```
Comment (ozscheyge) [inline restdocs-api-spec-openapi-generator/src/test/kotlin/com/epages/restdocs/apispec/openapi2/OpenApi20GeneratorTest.kt:234]: ...in POST request as formData

File: restdocs-api-spec-openapi-generator/src/test/kotlin/com/epages/restdocs/apispec/openapi2/OpenApi20GeneratorTest.kt [hunk 2]
```diff
@@ -832,6 +878,41 @@ class OpenApi20GeneratorTest {
...
+        return RequestModel(
+                path = path,
+                method = method,
+                contentType = "application/x-www-form-urlencoded",
+                schema = schema,
+                securityRequirements = SecurityRequirements(
+                        type = OAUTH2,
+                        requiredScopes = listOf("prod:c")
+                ),
+                headers = listOf(
```
Comment (ozscheyge) [inline restdocs-api-spec-openapi-generator/src/test/kotlin/com/epages/restdocs/apispec/openapi2/OpenApi20GeneratorTest.kt:891]: This should not be needed

File: restdocs-api-spec-openapi-generator/src/test/kotlin/com/epages/restdocs/apispec/openapi2/OpenApi20GeneratorTest.kt [hunk 3]
```diff
@@ -832,6 +878,41 @@ class OpenApi20GeneratorTest {
         )
     }
 
+    private fun productRequest(schema: Schema? = null, path: String = "/products", method: HTTPMethod = HTTPMethod.POST): RequestModel {
+        return RequestModel(
+                path = path,
+                method = method,
+                contentType = "application/x-www-form-urlencoded",
+                schema = schema,
+                securityRequirements = SecurityRequirements(
```
Comment (ozscheyge) [inline restdocs-api-spec-openapi-generator/src/test/kotlin/com/epages/restdocs/apispec/openapi2/OpenApi20GeneratorTest.kt:887]: This should not be needed

File: restdocs-api-spec-openapi-generator/src/test/kotlin/com/epages/restdocs/apispec/openapi2/OpenApi20GeneratorTest.kt [hunk 4]
```diff
@@ -230,6 +230,26 @@ class OpenApi20GeneratorTest {
...
+        val api = givenResourceModelsWithApplicationForm(HTTPMethod.POST)
+
+        val openapi = whenOpenApiObjectGenerated(api)
+
+        thenPostRequestShouldHaveFormDataParameters(openapi, api)
+        thenValidateOpenApi(openapi)
+    }
+
+    @Test
+    fun `should handle urlencoded body in PUT request as a formData not query string`() {
```
Comment (ozscheyge) [inline restdocs-api-spec-openapi-generator/src/test/kotlin/com/epages/restdocs/apispec/openapi2/OpenApi20GeneratorTest.kt:244]: ...in PUT request as formData

File: restdocs-api-spec-openapi-generator/src/main/kotlin/com/epages/restdocs/apispec/openapi2/OpenApi20Generator.kt [hunk 5]
```diff
@@ -412,7 +420,7 @@ object OpenApi20Generator {
         }
     }
 
-    private fun requestParameterDescriptor2Parameter(parameterDescriptor: ParameterDescriptor): QueryParameter {
+    private fun requestParameterDescriptor2QueryParameter(parameterDescriptor: ParameterDescriptor): QueryParameter {
```
Comment (ozscheyge) [inline restdocs-api-spec-openapi-generator/src/main/kotlin/com/epages/restdocs/apispec/openapi2/OpenApi20Generator.kt:423]: This could be combined with the function below by using generics, but the current solution is also fine and expressive

File: restdocs-api-spec-openapi3-generator/src/test/kotlin/com/epages/restdocs/apispec/openapi3/OpenApi3GeneratorTest.kt [hunk 6]
```diff
@@ -730,6 +778,30 @@ class OpenApi3GeneratorTest {
         )
     }
 
+    private fun getProductRequestAsFormData(method: HTTPMethod, getSecurityRequirement: () -> SecurityRequirements = ::getOAuth2SecurityRequirement): RequestModel {
```
Comment (ozscheyge) [inline restdocs-api-spec-openapi3-generator/src/test/kotlin/com/epages/restdocs/apispec/openapi3/OpenApi3GeneratorTest.kt:781]: The `get` in `getProductRequestAsFormData` comes from the HTTP method GET. Thus I'd just name it
`productRequestAsFormData` (the method is defined by the first parameter)

File: restdocs-api-spec-openapi3-generator/src/test/kotlin/com/epages/restdocs/apispec/openapi3/OpenApi3GeneratorTest.kt [hunk 7]
```diff
@@ -730,6 +778,30 @@ class OpenApi3GeneratorTest {
...
+        return RequestModel(
+                path = "/products/{id}-{subId}",
```
Comment (ozscheyge) [inline restdocs-api-spec-openapi3-generator/src/test/kotlin/com/epages/restdocs/apispec/openapi3/OpenApi3GeneratorTest.kt:783]: This is probably due to copy&paste from another given method, but does just distract here. I'd simplify it to:
`path = "/products/{id}",`

File: restdocs-api-spec-openapi3-generator/src/test/kotlin/com/epages/restdocs/apispec/openapi3/OpenApi3GeneratorTest.kt [hunk 8]
```diff
@@ -178,14 +178,47 @@ class OpenApi3GeneratorTest {
...
+    fun `should extract multiple parameters when separated by delimiter`() {
         givenResourceWithMultiplePathParameters()
 
         whenOpenApiObjectGenerated()
 
         thenMultiplePathParametersExist()
     }
 
+    @Test
+    fun `should handle urlencoded body in POST request as a request body not query string`() {
```
Comment (ozscheyge) [inline restdocs-api-spec-openapi3-generator/src/test/kotlin/com/epages/restdocs/apispec/openapi3/OpenApi3GeneratorTest.kt:190]: should treat urlencoded body in POST request as request body and not as query

File: restdocs-api-spec-openapi3-generator/src/test/kotlin/com/epages/restdocs/apispec/openapi3/OpenApi3GeneratorTest.kt [hunk 9]
```diff
@@ -178,14 +178,47 @@ class OpenApi3GeneratorTest {
...
+
+        givenResourceWithFormDataSentAs(method)
+
+        whenOpenApiObjectGenerated()
+
+        thenResourceHasFormDataInRequestBodyNotAsQueryParameters(method.toString().toLowerCase())
+    }
+
+    @Test
+    fun `should handle urlencoded body in PUT request as a request body not query string`() {
```
Comment (ozscheyge) [inline restdocs-api-spec-openapi3-generator/src/test/kotlin/com/epages/restdocs/apispec/openapi3/OpenApi3GeneratorTest.kt:201]: should treat urlencoded body in PUT request as request body and not as query

File: restdocs-api-spec-openapi3-generator/src/test/kotlin/com/epages/restdocs/apispec/openapi3/OpenApi3GeneratorTest.kt [hunk 10]
```diff
@@ -178,14 +178,47 @@ class OpenApi3GeneratorTest {
...
+
+        givenResourceWithFormDataSentAs(method)
+
+        whenOpenApiObjectGenerated()
+
+        thenResourceHasFormDataInRequestBodyNotAsQueryParameters(method.toString().toLowerCase())
+    }
+
+    fun thenResourceHasFormDataInRequestBodyNotAsQueryParameters(method: String) {
+        val productGetByIdPath = "paths./products/{id}-{subId}.$method"
```
Comment (ozscheyge) [inline restdocs-api-spec-openapi3-generator/src/test/kotlin/com/epages/restdocs/apispec/openapi3/OpenApi3GeneratorTest.kt:212]: This would need to be adapted to `/products/{id}` if the suggestion below is followed

File: restdocs-api-spec-openapi3-generator/src/test/kotlin/com/epages/restdocs/apispec/openapi3/OpenApi3GeneratorTest.kt [hunk 11]
```diff
@@ -178,14 +178,47 @@ class OpenApi3GeneratorTest {
...
+        val method = HTTPMethod.PUT
+
+        givenResourceWithFormDataSentAs(method)
+
+        whenOpenApiObjectGenerated()
+
+        thenResourceHasFormDataInRequestBodyNotAsQueryParameters(method.toString().toLowerCase())
+    }
+
+    fun thenResourceHasFormDataInRequestBodyNotAsQueryParameters(method: String) {
```
Comment (ozscheyge) [inline restdocs-api-spec-openapi3-generator/src/test/kotlin/com/epages/restdocs/apispec/openapi3/OpenApi3GeneratorTest.kt:211]: thenResourceHasFormDataInRequestBody**And**NotAsQueryParameters

File: restdocs-api-spec-openapi-generator/src/main/kotlin/com/epages/restdocs/apispec/openapi2/OpenApi20Generator.kt (hunk 5 above)
Comment (afronski) [reply restdocs-api-spec-openapi-generator/src/main/kotlin/com/epages/restdocs/apispec/openapi2/OpenApi20Generator.kt:423]: Great, so I will leave it as is.

**Comment by afronski** [comment]
@ozscheyge I have introduced improvements requested by you, and also added the implementation for the aforementioned case with empty schema response for OpenAPI 3.0. 

Feel free to review once again and provide feedback. If implementation is okay, I think it should definitely close #113 without a need for introducing additional issues after.

**Comment by bigDDDeveloper** [comment]
Hello @afronski : Kindly confirm the jar version in which this issue is fixed as i am getting empty object schema with "com.epages:restdocs-api-spec-mockmvc:0.11.4"
